--- # webserver
server:
  port: 8080
  context-path: /
  session:
    timeout: 1800

--- # logging
logging:
  level:
    root: INFO
    com: 
      digitalchina: INFO
      
#    org.springframework.web.servlet.mvc: debug
#    org.mybatis: debug

--- # datasource
spring:
  datasource:
    url: jdbc:mysql://221.178.232.93:3307/springboot-demo?useSSL=false
    username: springboot
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 1
    maximum-pool-size: 10
    connection-timeout: 5000

--- # template
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

--- # mybatis
mybatis:
  config-location: classpath:mybatis-config.xml #增加mybatis xml风格的支持
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.digitalchina.appname.api.model

--- # eureka
spring:
  application:
    name: spring-boot-demo
    groupName: mscx
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 10000
        maxInterval: 10000
        maxAttempts: 6    #客户端启动时，如果服务端不可用，重试
       
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    registry-fetch-interval-seconds: 10   #生产环境上，这个值得设为30
    initial-instance-info-replication-interval-seconds: 5  #生产环境上，这个值得设为10
    serviceUrl:
      defaultZone: http://mscx-eureka-server-mgr.eastdc.cn:82/eureka/,http://mscx-eureka-server-mgr-2.eastdc.cn:82/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  #生产环境上，这个值得设为30
    lease-expiration-duration-in-seconds: 10   #生产环境上，这个值得设为30
  server:
    waitTimeInMsWhenSyncEmpty: 0
    registrySyncRetries: 0

spring-boot-demo:    
  ribbon:
    serverListRefreshInterval: 5000   #生产环境上，这个值得设为30000

platform:
  invokeTrace:
    enabled: false
    url: http://invoke-trace.eastdc.cn:82/invoke.do
  ribbon:
    httpClient:
      timeToLiveInSeconds: 30
      maxConnectionsTotal: 100
      maxConcurrentPerRoute: 30
      maxConnectionTimeoutInSeconds: 1
      maxReadTimeoutInSeconds: 5
      maxRetryAttempts: 4
  httpClient:
    timeToLiveInSeconds: 30
    maxConnectionsTotal: 100
    maxConcurrentPerRoute: 30
    maxConnectionTimeoutInSeconds: 5
    maxReadTimeoutInSeconds: 10
    
cas:
  loginSccessBackUrl: http://localhost:8080/login/cas
  loginUrl: http://mscxsso.eastdc.cn:82
  loginSuccessBackUrl: http://localhost:8080/login/cas
  providerKey: key4CasAuthenticationProvider
  ignoreAuthUrls: /lib/**,/,/favicon.ico
  rejectPublicInvocations: false
  authPomptType: true
  filterProcessesUrl: /login/cas
  alwaysTarget: true
  targetUrl: http://localhost:8080
  redirectCurrentUrl: false

sc:
  pCode: demo
  apiKey: 543df6e9aed348dc85e05593b1c9c24d
  allApplicationUrl: http://mscxupms.eastdc.cn:82/api/allApplication.json
  userInfoUrl: http://mscxupms.eastdc.cn:82/api/userInfo.json
  authApplicationUrl: http://mscxupms.eastdc.cn:82/api/authApplication.json
  httpConnectionTimeout: 60
  
upms:
  url: http://mscxupms.eastdc.cn:82
  interceptor:
    patterns: /**/*.do,/
